### PR TITLE
WIP:slack notification feature

### PR DESCRIPTION
**Pull request by medinae**
#16

### CODE REVIEW

**Comment by medinae** [comment]
I'll try to find time to polish and finish it asap.

**Comment by medinae** [comment]
- [ ] Implement strategy pattern with a ChainNotificator and related CompilerPass

- [ ] Finish and polish Message class and slack notificator

- [ ] Implement tests

**Comment by lyrixx** [comment]
Hello @medinae 

Thanks for tacking care of this issue.

I really like very simple code and It looks like you are building something able to handle many options / notifier. For now I use only slack so I'm totally fine with something like `$this->get('slack.notifier')->sendToSlack($fortunes)` directly in the controller. 

There are no need to create an event nor to create a ChainNotificator and or Compiler pass.

Finally, I don't think we need https://github.com/cleentfaar/CLSlackBundle. It looks not maintained anymore. Instead you can use http://docs.php-http.org/en/latest/ ;)

**Comment by lyrixx** [comment]
We can use symfony/notification instead :)

**Comment by medinae** [comment]
Ouuuuch ! Old times. Switched to go since a couple of time now.
Will check about that component ! Thanks.

I'll close that PR.

**Pull request closed without merging**
